import type { Metadata } from "next";
import { LegalPageShell } from "@/components/LegalPageShell";

export const metadata: Metadata = {
  title: "Risk Disclosure",
  description:
    "Important risk warnings about trading financial instruments and the use of the RiskSent platform.",
  alternates: { canonical: "https://risksent.com/risk-disclosure" },
};

export default function RiskDisclosurePage() {
  return (
    <LegalPageShell
      title="Risk Disclosure"
      subtitle="Trading financial instruments involves substantial risk. Read this page carefully before using RiskSent to make trading decisions."
      lastUpdated="April 20, 2026"
    >
      <h2>1. General risk warning</h2>
      <p>
        Trading financial instruments — including foreign exchange (forex),
        contracts for difference (CFDs), futures, options, stocks,
        cryptocurrencies and other derivatives — involves a{" "}
        <strong>high level of risk</strong> and may not be suitable for every
        investor. You could lose some or all of your invested capital, and in
        some products you could lose more than your initial deposit. Do not
        trade with money you cannot afford to lose.
      </p>

      <h2>2. RiskSent is a software platform</h2>
      <p>
        <strong>
          RiskSent is not a broker, exchange, financial advisor, asset manager
          or signal provider.
        </strong>{" "}
        We supply software tools that help traders backtest strategies,
        journal their trades, compute risk metrics and receive alerts. We do
        not:
      </p>
      <ul>
        <li>execute or route orders;</li>
        <li>hold, custody or transfer your funds;</li>
        <li>guarantee any investment result;</li>
        <li>provide personalised investment advice.</li>
      </ul>

      <h2>3. Backtesting and simulated results</h2>
      <p>
        Backtests and simulated performance shown in the Platform are{" "}
        <strong>hypothetical</strong>. They are based on historical data and
        assumptions (commissions, spreads, slippage, fill logic) that may not
        reflect real market conditions. Simulated results:
      </p>
      <ul>
        <li>
          have the benefit of hindsight and do not involve financial risk;
        </li>
        <li>
          do not account for market impact, liquidity shocks, partial fills
          or broker-specific behaviour;
        </li>
        <li>
          can be affected by data gaps, corporate actions or time-zone
          inconsistencies.
        </li>
      </ul>
      <p>
        <strong>
          Past performance — whether real or simulated — is not indicative of
          future results.
        </strong>
      </p>

      <h2>4. Live alerts and automation</h2>
      <p>
        Live monitoring and Telegram alerts depend on external services
        (brokers, data APIs, messaging networks) that can be delayed,
        unavailable or provide inaccurate data. Alerts should be treated as
        support tools, not as a primary circuit-breaker. You remain fully
        responsible for monitoring your open positions.
      </p>

      <h2>5. AI Coach</h2>
      <p>
        AI Coach outputs are generated by large language models and may be
        incomplete, outdated, biased or factually incorrect. Use AI Coach
        only as a starting point for your own analysis — never as a
        substitute for your due diligence, your broker rules, or advice from
        a licensed professional.
      </p>

      <h2>6. Prop firms and third-party rules</h2>
      <p>
        If you trade with a prop firm, a funded account or a broker with
        specific rules (drawdown limits, maximum daily loss, news-trading
        restrictions, consistency rules, etc.), you are solely responsible
        for reading and following those rules. RiskSent’s risk features are
        configured by you and cannot guarantee compliance with any
        third-party program.
      </p>

      <h2>7. Tax and regulation</h2>
      <p>
        Tax treatment of trading activity depends on your country of
        residence and personal circumstances and may change over time.
        RiskSent does not provide tax or legal advice. Consult a qualified
        professional for your situation.
      </p>

      <h2>8. Your responsibility</h2>
      <p>
        By using RiskSent you acknowledge and accept that:
      </p>
      <ul>
        <li>
          you understand the risks associated with the financial instruments
          you trade;
        </li>
        <li>
          all trading decisions are yours alone and made at your own risk;
        </li>
        <li>
          RiskSent will not be liable for trading losses, missed trades,
          delayed alerts, inaccurate data or third-party outages.
        </li>
      </ul>

      <h2>9. Need a break?</h2>
      <p>
        If trading is affecting your mental health or finances, please stop
        and seek help. In the EU you can reach non-profit organisations such
        as <em>Gamblers Anonymous</em> or equivalent services in your country.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions about this notice? Write to{" "}
        <a href="mailto:support@risksent.com">support@risksent.com</a>.
      </p>
    </LegalPageShell>
  );
}
