/** Common MT4/MT5 broker server names for add-account picker (user can still type any server). */
export type PopularBrokerServer = {
  broker: string;
  server: string;
};

export const POPULAR_BROKER_SERVERS: PopularBrokerServer[] = [
  { broker: "Admirals (Admiral Markets)", server: "AdmiralMarkets-Demo" },
  { broker: "Admirals (Admiral Markets)", server: "AdmiralMarkets-Live" },
  { broker: "Alpari", server: "Alpari-Demo" },
  { broker: "Alpari", server: "Alpari-Real" },
  { broker: "AvaTrade", server: "Ava-Demo" },
  { broker: "AvaTrade", server: "Ava-Real" },
  { broker: "BlackBull Markets", server: "BlackBullMarkets-Demo" },
  { broker: "BlackBull Markets", server: "BlackBullMarkets-Live" },
  { broker: "Capital.com", server: "Capital.com-Demo" },
  { broker: "Capital.com", server: "Capital.com-Real" },
  { broker: "CMC Markets", server: "CMCMarkets-Demo" },
  { broker: "CMC Markets", server: "CMCMarkets-Live" },
  { broker: "Darwinex", server: "Darwinex-Demo" },
  { broker: "Darwinex", server: "Darwinex-Live" },
  { broker: "Doo Prime", server: "DooTechnology-Demo" },
  { broker: "Doo Prime", server: "DooTechnology-Live" },
  { broker: "Eightcap", server: "Eightcap-Demo" },
  { broker: "Eightcap", server: "Eightcap-Live" },
  { broker: "Exness", server: "Exness-MT5Trial" },
  { broker: "Exness", server: "Exness-MT5Real" },
  { broker: "Exness", server: "Exness-MT4Trial" },
  { broker: "Exness", server: "Exness-MT4Real" },
  { broker: "FBS", server: "FBS-Demo" },
  { broker: "FBS", server: "FBS-Real" },
  { broker: "FP Markets", server: "FPMarkets-Demo" },
  { broker: "FP Markets", server: "FPMarkets-Live" },
  { broker: "FXCM", server: "FXCM-DEMO01" },
  { broker: "FXCM", server: "FXCM-REAL01" },
  { broker: "FXOpen", server: "FXOpen-Demo" },
  { broker: "FXOpen", server: "FXOpen-Live" },
  { broker: "FXPrimus", server: "FXPrimus-Demo" },
  { broker: "FXPrimus", server: "FXPrimus-Live" },
  { broker: "FXTM (ForexTime)", server: "ForexTimeFXTM-Demo01" },
  { broker: "FXTM (ForexTime)", server: "ForexTimeFXTM-Live01" },
  { broker: "Global Prime", server: "GlobalPrime-Demo" },
  { broker: "Global Prime", server: "GlobalPrime-Live" },
  { broker: "GO Markets", server: "GOMarkets-Demo" },
  { broker: "GO Markets", server: "GOMarkets-Live" },
  { broker: "HFM (HotForex)", server: "HFMarkets-Demo" },
  { broker: "HFM (HotForex)", server: "HFMarkets-Live" },
  { broker: "IC Markets", server: "ICMarketsSC-Demo" },
  { broker: "IC Markets", server: "ICMarketsSC-Live" },
  { broker: "IC Markets", server: "ICMarkets-Demo" },
  { broker: "IC Markets", server: "ICMarkets-Live" },
  { broker: "IG", server: "IG-DEMO" },
  { broker: "IG", server: "IG-LIVE" },
  { broker: "JustMarkets", server: "JustMarkets-Demo" },
  { broker: "JustMarkets", server: "JustMarkets-Live" },
  { broker: "Libertex / Forex Club", server: "Libertex-Demo" },
  { broker: "Libertex / Forex Club", server: "Libertex-Live" },
  { broker: "LiteFinance", server: "LiteFinance-Demo" },
  { broker: "LiteFinance", server: "LiteFinance-Live" },
  { broker: "Moneta Markets", server: "MonetaMarkets-Demo" },
  { broker: "Moneta Markets", server: "MonetaMarkets-Live" },
  { broker: "OANDA", server: "Oanda-v20 Practice" },
  { broker: "OANDA", server: "Oanda-v20 Live" },
  { broker: "OctaFX", server: "OctaFX-Demo" },
  { broker: "OctaFX", server: "OctaFX-Live" },
  { broker: "Pepperstone", server: "Pepperstone-Demo" },
  { broker: "Pepperstone", server: "Pepperstone-Live" },
  { broker: "Plus500", server: "Plus500-Demo" },
  { broker: "Plus500", server: "Plus500-Live" },
  { broker: "RoboForex", server: "RoboForex-Demo" },
  { broker: "RoboForex", server: "RoboForex-Pro" },
  { broker: "Saxo Bank", server: "SaxoTrader-DEMO" },
  { broker: "Saxo Bank", server: "SaxoTrader-GO-LIVE" },
  { broker: "Swissquote", server: "Swissquote-Demo" },
  { broker: "Swissquote", server: "Swissquote-Live" },
  { broker: "ThinkMarkets", server: "ThinkMarkets-Demo" },
  { broker: "ThinkMarkets", server: "ThinkMarkets-Live" },
  { broker: "Tickmill", server: "Tickmill-Demo" },
  { broker: "Tickmill", server: "Tickmill-Live" },
  { broker: "TMGM", server: "TMGM-Demo" },
  { broker: "TMGM", server: "TMGM-Live" },
  { broker: "Trade Nation", server: "TradeNation-Demo" },
  { broker: "Trade Nation", server: "TradeNation-Live" },
  { broker: "Traders Trust", server: "TradersTrust-Demo" },
  { broker: "Traders Trust", server: "TradersTrust-Live" },
  { broker: "Vantage", server: "VantageInternational-Demo" },
  { broker: "Vantage", server: "VantageInternational-Live" },
  { broker: "XM", server: "XMGlobal-Demo" },
  { broker: "XM", server: "XMGlobal-Real" },
  { broker: "XTB", server: "XTB-Demo" },
  { broker: "XTB", server: "XTB-Real" }
].sort((a, b) => a.broker.localeCompare(b.broker) || a.server.localeCompare(b.server));

export const SUPPORT_BROKER_REQUEST_MAILTO =
  "mailto:support@risksent.com?subject=" + encodeURIComponent("request broker add");
